- task: AzureFileCopy@4
  inputs:
    azureSubscription: 'Pay-As-You-Go(5f32c139-c39a-4e3f-9cb4-a786b8dc7885)'
    Destination: 'AzureBlob'
    storage: 'michaelslabwebstore'
trigger:
- master
- task: ArchiveFiles@2
  inputs:
- task: AzureFileCopy@4
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    azureSubscription: 'Pay-As-You-Go(1)(5f32c139-c39a-4e3f-9cb4-a786b8dc7885)'
    Destination: 'AzureBlob'
    storage: 'michaelslabwebstore'
    ContainerName: '$web'
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: '7z'
    archiveFile: '
 task: AzureFileCopy@4
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    Destination: 'AzureBlob'
    storage: 'michaelslabwebstore'
    ContainerName: 'web$'
    replaceExistingArchive: true
    verbose: true

 -task: AzureWebApp@1
 inputs:
    azureSubscription: '5f32c139-c39a-4e3f-9cb4-a786b8dc7885'
    appName: 'game_of_life'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip' 
- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '*.zip'
    cleanDestinationFolder: true

## adding copy
- task: AzureFileCopy@4
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    azureSubscription: 'Pay-As-You-Go(5f32c139-c39a-4e3f-9cb4-a786b8dc7885)'
    Destination: 'AzureBlob'
    storage: 'michaelslabwebstore'



