
trigger:
- master
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: '7z'
    archiveFile: '- task: AzureFileCopy@4
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'''
    Destination: 'AzureBlob'
    storage: 'michaelslabwebstore'
    ContainerName: 'web$'
    replaceExistingArchive: true
    verbose: true


 -task: AzureWebApp@1
 inputs:
    azureSubscription: '<Azure service connection>'
    appName: 'game_of_life'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip' 



